"""entry_songs

Revision ID: 03095ba431a8
Revises: 0e3db2d29d5c
Create Date: 2026-07-14 02:00:46.697752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03095ba431a8'
down_revision: Union[str, None] = '0e3db2d29d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_songs',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=11), nullable=False),
    sa.Column('start_seconds', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_entry_songs_entry_id'), 'entry_songs', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_songs_entry_id'), table_name='entry_songs')
    op.drop_table('entry_songs')
    # ### end Alembic commands ###
