"""week4_lock_system

Revision ID: 0e3db2d29d5c
Revises: 51dc9c165234
Create Date: 2026-07-14 01:10:35.604931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3db2d29d5c'
down_revision: Union[str, None] = '51dc9c165234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unlock_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed the single site_config row.  Default: 20th June 2027
    op.execute(
        "INSERT INTO site_config (id, unlock_date) VALUES (1, '2027-06-20 00:00:00+00')"
    )
    op.create_table('entry_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('lock_type', sa.String(length=10), nullable=False),
    sa.Column('passcode_hash', sa.String(length=255), nullable=True),
    sa.Column('riddle_question', sa.String(length=500), nullable=True),
    sa.Column('riddle_answer_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_locks_entry_id'), 'entry_locks', ['entry_id'], unique=True)
    op.create_index(op.f('ix_entry_locks_id'), 'entry_locks', ['id'], unique=False)
    op.create_table('entry_unlocks',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'user_id'),
    sa.UniqueConstraint('entry_id', 'user_id', name='uq_entry_unlock')
    )
    # server_default prevents NOT NULL constraint violation on existing rows
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_table('entry_unlocks')
    op.drop_index(op.f('ix_entry_locks_id'), table_name='entry_locks')
    op.drop_index(op.f('ix_entry_locks_entry_id'), table_name='entry_locks')
    op.drop_table('entry_locks')
    op.drop_table('site_config')
    # ### end Alembic commands ###
