"""create_threads_and_entries_tables

Revision ID: 51dc9c165234
Revises: 4c391119f352
Create Date: 2026-07-14 00:26:23.084464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51dc9c165234'
down_revision: Union[str, None] = '4c391119f352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_id'), 'threads', ['id'], unique=False)
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('media_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_author_id'), 'entries', ['author_id'], unique=False)
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    op.create_index(op.f('ix_entries_thread_id'), 'entries', ['thread_id'], unique=False)
    op.create_table('thread_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_invites_code'), 'thread_invites', ['code'], unique=True)
    op.create_index(op.f('ix_thread_invites_id'), 'thread_invites', ['id'], unique=False)
    op.create_index(op.f('ix_thread_invites_thread_id'), 'thread_invites', ['thread_id'], unique=False)
    op.create_table('thread_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_thread_member')
    )
    op.create_index(op.f('ix_thread_members_id'), 'thread_members', ['id'], unique=False)
    op.create_index(op.f('ix_thread_members_thread_id'), 'thread_members', ['thread_id'], unique=False)
    op.create_index(op.f('ix_thread_members_user_id'), 'thread_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_members_user_id'), table_name='thread_members')
    op.drop_index(op.f('ix_thread_members_thread_id'), table_name='thread_members')
    op.drop_index(op.f('ix_thread_members_id'), table_name='thread_members')
    op.drop_table('thread_members')
    op.drop_index(op.f('ix_thread_invites_thread_id'), table_name='thread_invites')
    op.drop_index(op.f('ix_thread_invites_id'), table_name='thread_invites')
    op.drop_index(op.f('ix_thread_invites_code'), table_name='thread_invites')
    op.drop_table('thread_invites')
    op.drop_index(op.f('ix_entries_thread_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_author_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_threads_id'), table_name='threads')
    op.drop_table('threads')
    # ### end Alembic commands ###
