"""add theme

Revision ID: 82fdce55bdb3
Revises: 03095ba431a8
Create Date: 2026-07-14 02:32:20.949794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fdce55bdb3'
down_revision: Union[str, None] = '03095ba431a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('theme', sa.String(length=20), server_default='classic', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'theme')
    # ### end Alembic commands ###
